name = "instock-bot"
main = "src/index.ts"
compatibility_date = "2024-10-22"

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "D1_DB"
database_name = "instock_db"
database_id = "0c171092-618e-42a8-93d7-8c0816a6d7ed"
preview_database_id = "0c171092-618e-42a8-93d7-8c0816a6d7ed"
